// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDomF2BDixcybDcuQqUn0CARB1lZ7o6n7M',
    appId: '1:587454946435:web:84dd5742e2aec2297ccfb6',
    messagingSenderId: '587454946435',
    projectId: 'pets-media-29963',
    authDomain: 'pets-media-29963.firebaseapp.com',
    storageBucket: 'pets-media-29963.appspot.com',
    measurementId: 'G-FTTR9CKFCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrNPlK5knW3VWtz0_HiTSsBkmfkBHJwlw',
    appId: '1:587454946435:android:6e7cc556894997887ccfb6',
    messagingSenderId: '587454946435',
    projectId: 'pets-media-29963',
    storageBucket: 'pets-media-29963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqDTn_YbVgprY_8gZI0eTeiZRe8pJCOk',
    appId: '1:587454946435:ios:9bc9e8a1ab72c67d7ccfb6',
    messagingSenderId: '587454946435',
    projectId: 'pets-media-29963',
    storageBucket: 'pets-media-29963.appspot.com',
    iosBundleId: 'com.example.omniBridgeAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqDTn_YbVgprY_8gZI0eTeiZRe8pJCOk',
    appId: '1:587454946435:ios:9bc9e8a1ab72c67d7ccfb6',
    messagingSenderId: '587454946435',
    projectId: 'pets-media-29963',
    storageBucket: 'pets-media-29963.appspot.com',
    iosBundleId: 'com.example.omniBridgeAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDomF2BDixcybDcuQqUn0CARB1lZ7o6n7M',
    appId: '1:587454946435:web:48c677cf1c1c97e87ccfb6',
    messagingSenderId: '587454946435',
    projectId: 'pets-media-29963',
    authDomain: 'pets-media-29963.firebaseapp.com',
    storageBucket: 'pets-media-29963.appspot.com',
    measurementId: 'G-SBCG03HGY3',
  );
}
